<a href="https://colab.research.google.com/github/ShrijalMaharjan/ML_from_scratch/blob/main/01%20Introduction_to_numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy

What will we cover?
  - Creating array
  - Multi dimensional array
  - Randomly generated arrays
  - Element wise operations
    - Comparison operations
    - LOGICAL OPERATIONS
  - Summarizing operations

### Single dimensional arrays

In [ ]:
import numpy as np

Creating arrays

In [ ]:
var = np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
new = np.array([1, 2, 3, 4])
new[2] = 5
print(new)

[1 2 5 4]


In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

Creating arrays with evenly spaced numbers within a specified range

In [ ]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Multidimensional Arrays

In [ ]:
np.zeros([5, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones([5, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Create an MD unit Array of size (5,2)

In [ ]:
np.ones([5, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Generate a random array of size (3, 5) with elements of your choice

In [ ]:
new = np.array([[1, 2, 3, 4, 5],
      [2, 3, 4, 5, 6],
      [3, 4, 5, 6, 7]])
new

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
# Update the element of an array with index

In [ ]:
new[0, 1] = 20
new

array([[ 1, 20,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7]])

In [ ]:
new[2] = [1, 1, 1, 1, 1]
new

array([[ 1, 20,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 1,  1,  1,  1,  1]])

In [ ]:
new[:, 2]= [2, 2, 2]
new

array([[ 1, 20,  2,  4,  5],
       [ 2,  3,  2,  5,  6],
       [ 1,  1,  2,  1,  1]])

### Random generated arrays
  - Numpy can create arrays filled with random numbers.
  - To ensure the reproducibility, you can set a seed using np.random.seed()
  - Everytime you can the code with np.random.seed(2), it will generate the exact same random numbers.


If you remove or change the seed values, the sequence of random numbers will be changed


In [ ]:
np.random.rand(5)

array([0.40569326, 0.18694049, 0.5320416 , 0.67957139, 0.71743318])

In [ ]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [ ]:
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [ ]:
np.random.randn(5, 2)

array([[ 0.18760323, -0.32986996],
       [-1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904],
       [ 1.15139101,  1.85733101]])

In [ ]:
np.random.seed(42)
np.random.randint(low=0, high=100, size= (5,2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

Elements wise operation

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [ ]:
# Comparison operations
# You can perform element wise comparison and create boolean arrays
a

array([0, 1, 2, 3, 4])

In [ ]:
a>=2

array([False, False,  True,  True,  True])

In [ ]:
# Summarizing
# NumPy provieds functions for summarizing array of data
a

array([0, 1, 2, 3, 4])

In [ ]:
# standard deviation
a.std()

1.4142135623730951

In [ ]:
# min value of an array
a.min()

0

In [ ]:
# max value of an array
a.max()

4

In [ ]:
# sum of the elements of an array
a.sum()

10